CREATE TABLE "JOB_MANAGER" (
    "ID" VARCHAR PRIMARY KEY,
    "USERNAME" VARCHAR,
    "STATUS" VARCHAR NOT NULL,
    "ERROR_MESSAGE" VARCHAR,
    "URL" VARCHAR,
    "QUEUED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "STARTED_AT" TIMESTAMP,
    "COMPLETED_AT" TIMESTAMP,
    "FAILED_AT" TIMESTAMP
);